### ISSUE TITLE
Image without any fill color specified do not appear in preview

### ISSUE THREAD

**Issue by jhopper28** [lloeki/svg-preview#11]
They render as white on white, so you can see the image.

Here's a sample SVG:
```
<path d="M56.14,28.375H35.274V7.506c0-1.809-1.462-3.271-3.274-3.271c-1.811,0-3.274,1.463-3.274,3.271v20.869H7.862
	c-1.813,0-3.274,1.464-3.274,3.272c0,1.807,1.462,3.27,3.274,3.27h20.863v20.869c0,1.809,1.464,3.272,3.274,3.272
	c1.813,0,3.274-1.464,3.274-3.272V34.918H56.14c1.811,0,3.272-1.463,3.272-3.27C59.412,29.839,57.95,28.375,56.14,28.375z"/>
```

**Comment by lloeki** [comment]
Hmm, transparency is explicitly handled with a checkerboard pattern, and this is what I see:

![screenshot 2015-05-24 10 18 37](https://cloud.githubusercontent.com/assets/75445/7787184/4d5ebe2c-01fe-11e5-96ff-13f5b70a8288.png)

**Comment by lloeki** [comment]
Ping if this is still a problem.

**Comment by jhopper28** [comment]
It works now…thanks!
